#!/bin/sh

if [ $# -eq 0 ]; then
    ssh seakylone@csil.cs.ucsb.edu
elif [ $# -eq 1 ]; then
    if [ $1 -ge 0 ] || [ $1 -le 48 ]; then
        number=$1
        if [ $1 -ne 0$1 ] && [ $1 -lt 10 ]; then
            number="0$1"
        fi
        ssh seakylone@csil-$number.cs.ucsb.edu
    fi
else
    echo "Usage: ./csil 39"
fi
exit 0
