#!/bin/bash
alias sbp="source ~/.bash_profile"
alias code="C:/Users/Seaky/AppData/Local/Programs/Microsoft\ VS\ Code/Code.exe"
alias cdpy="cd C:/Users/Seaky/AppData/Local/Programs/Python/Python38/"
alias cdpyf="cd C:/Users/Seaky/AppData/Local/Programs/Python/Python38/Python\ Files"
alias cddt="cd C:/Users/Seaky/Desktop/"
alias cdwm="cd C:/Users/Seaky/Desktop/Win-Mac"
alias cdm="cd C:/Users/Seaky/AndroidStudioProjects/Moments"
alias cdgg="cd C:/Users/Seaky/AndroidStudioProjects/GoGaucho-Android"
alias cdgg="cd C:/Users/Seaky/AndroidStudioProjects/GoGaucho-Android"
alias cdrm="cd C:/Users/Seaky/AndroidStudioProjects/RandomMenu"
alias cdsmp="cd C:/Users/Seaky/source/repos/SMPlayer"
alias cdws="cd C:/War\ Song"
alias gitup="~/./gitup"
alias pygitup="~/./pygitup"
alias csil="~/./csil"
alias python="C:/Users/Seaky/AppData/Local/Programs/Python/Python38/python.exe"
alias python3="C:/Users/Seaky/AppData/Local/Programs/Python/Python38/python.exe"